### PR TITLE
Issue67 local houseprint config

### PR DESCRIPTION
**Pull request by JrtPec**
#67

So now the website tries 3 times to load the houseprint.
1. As default from the houseprint module (which uses the config file in the opengrid library)
2. Using the json path specified in opengrid.cfg (website version)
3. Using the cached version

### CODE REVIEW

**Comment by JrtPec** [comment]
So @saroele if I understand correctly, first we merge into master, then we merge master into the enquiry branch, and if I pull on the server it is linked to that branch?

**Comment by saroele** [comment]
Yep, that's the idea.  However, you can choose which branch you pull on the droplet:
`
git pull origin branchname
`
See also #69, so you can immediately do `git pull origin gridcamp`

I'll merge this into master AND from there into gridcamp and CORE-enquiry right now.

**Comment by JrtPec** [comment]
I just did a simple `hp.init_tmpo()`, so it'll connect with the sqlite on the default location. Is this good for the server, or does it need a special path?

**Comment by saroele** [comment]
There is a special path on the droplet, but it is specified in the cfg file.  Here's the info:

```
[tmpo]
#the database will be located in /usr/local/data/.tmpo/
data: /usr/local/data
```

**Comment by JrtPec** [comment]
Ok so I'll probably need to add

```
try:
    hp.init_tmpo(path_to_tmpo_data=c.get('tmpo', 'data'))
except:
    hp.init_tmpo()
```

**Pull request merged**
