### PR TITLE
plottable objects with titles and descriptions

### PR DESCRIPTION
**Pull request by JrtPec**
TODO Change descriptions

### CODE REVIEW

**Comment by JrtPec** [comment]
@saroele if you change the descriptions for the three analyses this can be merged

**Comment by saroele** [comment]
Hi @JrtPec 
I added the descriptions (can always be improved, but ok as first start).  
I did not manage to put line breaks in my string though.  You know how to do that? 

I'll make a pull request too, you can merge it in master if it works fine. 
Good work :-)

**Comment by wouterh** [comment]
this ends up in HTML eventually, right?

Put `<br/>` in your description to have a line break.

**Comment by JrtPec** [comment]
Should work, but I think you need to let Jinja (the template parser) know it is safe content. So in `sensor.html` put `{{ analysis.describtion|safe }}`

I'll test it tonight.

**Comment by saroele** [comment]
ok, I can also test that tonight.

**Pull request merged**
